import { KNOWN_USER_SCOPES } from "@/types/api/user";
import { useUserContext } from "@/contexts/UserContext";
import { useCallback } from "react";

export enum HORSES_PAGE_SCOPES_ACTIONS {
  CREATE_HORSE = "CREATE_HORSE",
  UPDATE_HORSE = "UPDATE_HORSE",
  UPDATE_HORSE_PEDIGREE = "UPDATE_HORSE_PEDIGREE",
  DELETE_HORSE = "DELETE_HORSE",
  CREATE_HORSE_DICTIONARY = "CREATE_HORSE_DICTIONARY",
  UPDATE_HORSE_DICTIONARY = "UPDATE_HORSE_DICTIONARY",
  DELETE_HORSE_DICTIONARY = "DELETE_HORSE_DICTIONARY",
  SEE_USER_DOCS = "SEE_USER_DOCS",
  SEE_DEVELOPER_DOCS = "SEE_DEVELOPER_DOCS",
}

export enum HORSE_SERVICE_SCOPES_ACTIONS {
  CREATE_HORSE_SERVICE = "create_horse_service",
  UPDATE_HORSE_SERVICE_NAME = "update_horse_service_name",
  UPDATE_HORSE_SERVICE_DESCRIPTION = "update_horse_service_description",
  UPDATE_HORSE_SERVICE = "update_horse_service",
  DELETE_HORSE_SERVICE = "delete_horse_service",
  RETRIEVE_HORSE_SERVICE = "retrieve_horse_service",
}

export const horsesPageScopesRegistry: Record<
  HORSES_PAGE_SCOPES_ACTIONS,
  KNOWN_USER_SCOPES[]
> = {
  [HORSES_PAGE_SCOPES_ACTIONS.CREATE_HORSE]: [
    KNOWN_USER_SCOPES.SUPERUSER,
    KNOWN_USER_SCOPES.ADMIN,
    KNOWN_USER_SCOPES.DEVELOPER,
  ],
  [HORSES_PAGE_SCOPES_ACTIONS.UPDATE_HORSE]: [
    KNOWN_USER_SCOPES.SUPERUSER,
    KNOWN_USER_SCOPES.ADMIN,
    KNOWN_USER_SCOPES.DEVELOPER,
  ],
  [HORSES_PAGE_SCOPES_ACTIONS.UPDATE_HORSE_PEDIGREE]: [
    KNOWN_USER_SCOPES.SUPERUSER,
    KNOWN_USER_SCOPES.ADMIN,
    KNOWN_USER_SCOPES.DEVELOPER,
  ],
  [HORSES_PAGE_SCOPES_ACTIONS.DELETE_HORSE]: [
    KNOWN_USER_SCOPES.SUPERUSER,
    KNOWN_USER_SCOPES.ADMIN,
    KNOWN_USER_SCOPES.DEVELOPER,
  ],
  [HORSES_PAGE_SCOPES_ACTIONS.CREATE_HORSE_DICTIONARY]: [
    KNOWN_USER_SCOPES.SUPERUSER,
    KNOWN_USER_SCOPES.ADMIN,
    KNOWN_USER_SCOPES.DEVELOPER,
  ],
  [HORSES_PAGE_SCOPES_ACTIONS.UPDATE_HORSE_DICTIONARY]: [
    KNOWN_USER_SCOPES.SUPERUSER,
    KNOWN_USER_SCOPES.ADMIN,
    KNOWN_USER_SCOPES.DEVELOPER,
  ],
  [HORSES_PAGE_SCOPES_ACTIONS.DELETE_HORSE_DICTIONARY]: [
    KNOWN_USER_SCOPES.SUPERUSER,
    KNOWN_USER_SCOPES.ADMIN,
    KNOWN_USER_SCOPES.DEVELOPER,
  ],
  [HORSES_PAGE_SCOPES_ACTIONS.SEE_USER_DOCS]: [
    KNOWN_USER_SCOPES.SUPERUSER,
    KNOWN_USER_SCOPES.ADMIN,
  ],
  [HORSES_PAGE_SCOPES_ACTIONS.SEE_DEVELOPER_DOCS]: [
    KNOWN_USER_SCOPES.SUPERUSER,
    KNOWN_USER_SCOPES.DEVELOPER,
  ],
};

export const horseServicePageScopesRegistry: Record<
  HORSE_SERVICE_SCOPES_ACTIONS,
  KNOWN_USER_SCOPES[]
> = {
  [HORSE_SERVICE_SCOPES_ACTIONS.CREATE_HORSE_SERVICE]: [
    KNOWN_USER_SCOPES.SUPERUSER,
    KNOWN_USER_SCOPES.DEVELOPER,
  ],
  [HORSE_SERVICE_SCOPES_ACTIONS.UPDATE_HORSE_SERVICE_NAME]: [
    KNOWN_USER_SCOPES.SUPERUSER,
    KNOWN_USER_SCOPES.DEVELOPER,
  ],
  [HORSE_SERVICE_SCOPES_ACTIONS.UPDATE_HORSE_SERVICE_DESCRIPTION]: [
    KNOWN_USER_SCOPES.SUPERUSER,
    KNOWN_USER_SCOPES.ADMIN,
    KNOWN_USER_SCOPES.DEVELOPER,
  ],
  [HORSE_SERVICE_SCOPES_ACTIONS.UPDATE_HORSE_SERVICE]: [
    KNOWN_USER_SCOPES.SUPERUSER,
    KNOWN_USER_SCOPES.ADMIN,
    KNOWN_USER_SCOPES.DEVELOPER,
  ],
  [HORSE_SERVICE_SCOPES_ACTIONS.DELETE_HORSE_SERVICE]: [
    KNOWN_USER_SCOPES.SUPERUSER,
    KNOWN_USER_SCOPES.DEVELOPER,
  ],
  [HORSE_SERVICE_SCOPES_ACTIONS.RETRIEVE_HORSE_SERVICE]: [
    KNOWN_USER_SCOPES.SUPERUSER,
    KNOWN_USER_SCOPES.ADMIN,
    KNOWN_USER_SCOPES.DEVELOPER,
  ],
};

export const useHorsePageActionScopes = () => {
  const { scopes } = useUserContext();

  const hasPermission = useCallback(
    (action: HORSES_PAGE_SCOPES_ACTIONS) => {
      return horsesPageScopesRegistry[action].some((scope) =>
        scopes.includes(scope),
      );
    },
    [scopes],
  );

  return { hasPermission };
};

export const useHorseServicePageActionScopes = () => {
  const { scopes } = useUserContext();

  const hasPermission = useCallback(
    (action: HORSE_SERVICE_SCOPES_ACTIONS) => {
      return horseServicePageScopesRegistry[action].some((scope) =>
        scopes.includes(scope),
      );
    },
    [scopes],
  );

  return { hasPermission };
};
