apiVersion: v1
kind: Pod
metadata:
  name: eqsitecms-frontend
  labels:
    components: frontend
spec:
  containers:
    - name: eqsitecms-frontend
      image: ghcr.io/igor-526/eqsitecms-frontend:latest
      ports:
        - containerPort: 5100
      resources:
        limits:
          cpu: 500m
          memory: 512Mi