name: Check

on:
  push:
    branches:
      - main
      - release
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install deps
        run: npm install

      - name: test
        run: npm test

      - name: lint
        run: npm run lint

      - name: type-check
        run: npx tsc --noEmit

      - name: build
        run: npm run build

